package com.work.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.work.entity.Events;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "events".
*/
public class EventsDao extends AbstractDao<Events, Long> {

    public static final String TABLENAME = "events";

    /**
     * Properties of entity Events.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, Long.class, "ID", true, "ID");
        public final static Property Type = new Property(1, String.class, "Type", false, "TYPE");
        public final static Property CreateTime = new Property(2, java.util.Date.class, "CreateTime", false, "CREATE_TIME");
        public final static Property Data = new Property(3, String.class, "Data", false, "DATA");
        public final static Property UpdateTime = new Property(4, java.util.Date.class, "UpdateTime", false, "UPDATE_TIME");
        public final static Property Status = new Property(5, String.class, "Status", false, "STATUS");
    }


    public EventsDao(DaoConfig config) {
        super(config);
    }
    
    public EventsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"events\" (" + //
                "\"ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: ID
                "\"TYPE\" TEXT NOT NULL ," + // 1: Type
                "\"CREATE_TIME\" INTEGER NOT NULL ," + // 2: CreateTime
                "\"DATA\" TEXT NOT NULL ," + // 3: Data
                "\"UPDATE_TIME\" INTEGER NOT NULL ," + // 4: UpdateTime
                "\"STATUS\" TEXT NOT NULL );"); // 5: Status
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"events\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Events entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindString(2, entity.getType());
        stmt.bindLong(3, entity.getCreateTime().getTime());
        stmt.bindString(4, entity.getData());
        stmt.bindLong(5, entity.getUpdateTime().getTime());
        stmt.bindString(6, entity.getStatus());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Events entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindString(2, entity.getType());
        stmt.bindLong(3, entity.getCreateTime().getTime());
        stmt.bindString(4, entity.getData());
        stmt.bindLong(5, entity.getUpdateTime().getTime());
        stmt.bindString(6, entity.getStatus());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Events readEntity(Cursor cursor, int offset) {
        Events entity = new Events( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ID
            cursor.getString(offset + 1), // Type
            new java.util.Date(cursor.getLong(offset + 2)), // CreateTime
            cursor.getString(offset + 3), // Data
            new java.util.Date(cursor.getLong(offset + 4)), // UpdateTime
            cursor.getString(offset + 5) // Status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Events entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType(cursor.getString(offset + 1));
        entity.setCreateTime(new java.util.Date(cursor.getLong(offset + 2)));
        entity.setData(cursor.getString(offset + 3));
        entity.setUpdateTime(new java.util.Date(cursor.getLong(offset + 4)));
        entity.setStatus(cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Events entity, long rowId) {
        entity.setID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Events entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Events entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
