package com.work.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.work.entity.Plans;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "plans".
*/
public class PlansDao extends AbstractDao<Plans, Long> {

    public static final String TABLENAME = "plans";

    /**
     * Properties of entity Plans.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, Long.class, "ID", true, "ID");
        public final static Property ProjectId = new Property(1, int.class, "ProjectId", false, "PROJECT_ID");
        public final static Property Data = new Property(2, String.class, "Data", false, "DATA");
        public final static Property CreateTime = new Property(3, java.util.Date.class, "CreateTime", false, "CREATE_TIME");
        public final static Property UpdateTime = new Property(4, java.util.Date.class, "UpdateTime", false, "UPDATE_TIME");
        public final static Property EndTime = new Property(5, java.util.Date.class, "EndTime", false, "END_TIME");
        public final static Property Status = new Property(6, String.class, "Status", false, "STATUS");
        public final static Property WeekNum = new Property(7, String.class, "WeekNum", false, "WEEK_NUM");
    }


    public PlansDao(DaoConfig config) {
        super(config);
    }
    
    public PlansDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"plans\" (" + //
                "\"ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: ID
                "\"PROJECT_ID\" INTEGER NOT NULL ," + // 1: ProjectId
                "\"DATA\" TEXT NOT NULL ," + // 2: Data
                "\"CREATE_TIME\" INTEGER NOT NULL ," + // 3: CreateTime
                "\"UPDATE_TIME\" INTEGER NOT NULL ," + // 4: UpdateTime
                "\"END_TIME\" INTEGER NOT NULL ," + // 5: EndTime
                "\"STATUS\" TEXT NOT NULL ," + // 6: Status
                "\"WEEK_NUM\" TEXT NOT NULL );"); // 7: WeekNum
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"plans\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Plans entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindLong(2, entity.getProjectId());
        stmt.bindString(3, entity.getData());
        stmt.bindLong(4, entity.getCreateTime().getTime());
        stmt.bindLong(5, entity.getUpdateTime().getTime());
        stmt.bindLong(6, entity.getEndTime().getTime());
        stmt.bindString(7, entity.getStatus());
        stmt.bindString(8, entity.getWeekNum());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Plans entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindLong(2, entity.getProjectId());
        stmt.bindString(3, entity.getData());
        stmt.bindLong(4, entity.getCreateTime().getTime());
        stmt.bindLong(5, entity.getUpdateTime().getTime());
        stmt.bindLong(6, entity.getEndTime().getTime());
        stmt.bindString(7, entity.getStatus());
        stmt.bindString(8, entity.getWeekNum());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Plans readEntity(Cursor cursor, int offset) {
        Plans entity = new Plans( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ID
            cursor.getInt(offset + 1), // ProjectId
            cursor.getString(offset + 2), // Data
            new java.util.Date(cursor.getLong(offset + 3)), // CreateTime
            new java.util.Date(cursor.getLong(offset + 4)), // UpdateTime
            new java.util.Date(cursor.getLong(offset + 5)), // EndTime
            cursor.getString(offset + 6), // Status
            cursor.getString(offset + 7) // WeekNum
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Plans entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setProjectId(cursor.getInt(offset + 1));
        entity.setData(cursor.getString(offset + 2));
        entity.setCreateTime(new java.util.Date(cursor.getLong(offset + 3)));
        entity.setUpdateTime(new java.util.Date(cursor.getLong(offset + 4)));
        entity.setEndTime(new java.util.Date(cursor.getLong(offset + 5)));
        entity.setStatus(cursor.getString(offset + 6));
        entity.setWeekNum(cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Plans entity, long rowId) {
        entity.setID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Plans entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Plans entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
