package com.work.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.work.entity.Projects;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "projects".
*/
public class ProjectsDao extends AbstractDao<Projects, Long> {

    public static final String TABLENAME = "projects";

    /**
     * Properties of entity Projects.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, Long.class, "ID", true, "ID");
        public final static Property Name = new Property(1, String.class, "Name", false, "NAME");
        public final static Property CreateTime = new Property(2, java.util.Date.class, "CreateTime", false, "CREATE_TIME");
        public final static Property UpdateTime = new Property(3, java.util.Date.class, "UpdateTime", false, "UPDATE_TIME");
    }


    public ProjectsDao(DaoConfig config) {
        super(config);
    }
    
    public ProjectsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"projects\" (" + //
                "\"ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: ID
                "\"NAME\" TEXT NOT NULL ," + // 1: Name
                "\"CREATE_TIME\" INTEGER NOT NULL ," + // 2: CreateTime
                "\"UPDATE_TIME\" INTEGER NOT NULL );"); // 3: UpdateTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"projects\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Projects entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindLong(3, entity.getCreateTime().getTime());
        stmt.bindLong(4, entity.getUpdateTime().getTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Projects entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindLong(3, entity.getCreateTime().getTime());
        stmt.bindLong(4, entity.getUpdateTime().getTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Projects readEntity(Cursor cursor, int offset) {
        Projects entity = new Projects( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ID
            cursor.getString(offset + 1), // Name
            new java.util.Date(cursor.getLong(offset + 2)), // CreateTime
            new java.util.Date(cursor.getLong(offset + 3)) // UpdateTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Projects entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setCreateTime(new java.util.Date(cursor.getLong(offset + 2)));
        entity.setUpdateTime(new java.util.Date(cursor.getLong(offset + 3)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Projects entity, long rowId) {
        entity.setID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Projects entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Projects entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
